version: "3.8"

services:
  basic-chess:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: BasicChess
        SERVICE_PORT: 8080
    container_name: basic-chess
    ports:
      - "5001:8080"
    networks:
      - chess-net

  controller:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: Controller
        SERVICE_PORT: 8080
    container_name: controller
    ports:
      - "5002:8080"
    networks:
      - chess-net

  devour-chess:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: DevourChess
        SERVICE_PORT: 8080
    container_name: devour-chess
    ports:
      - "5004:8080"
    networks:
      - chess-net

  real-chess:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: RealChess
        SERVICE_PORT: 8080
    container_name: real-chess
    ports:
      - "5003:8080"
    networks:
      - chess-net

  tui:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: TUI
        SERVICE_PORT: 8080
    container_name: tui
    ports:
      - "5005:8080"
    networks:
      - chess-net
    stdin_open: true
    tty: true

  gui:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: GUI
        SERVICE_PORT: 8080
    container_name: gui
    ports:
      - "5006:8080"
    networks:
      - chess-net
    environment:
      - DISPLAY=host.docker.internal:0.0
      - PRISM_ORDER=sw
      - JAVAFX_USE_VSYNC=false
      - GDK_BACKEND=x11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  xml:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: XML
        SERVICE_PORT: 8080
    container_name: xml
    ports:
      - "5007:8080"
    networks:
      - chess-net

  json:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: JSON
        SERVICE_PORT: 8080
    container_name: json
    ports:
      - "5008:8080"
    networks:
      - chess-net

  api:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: API
        SERVICE_PORT: 8080
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - chess-net

  database:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        SERVICE_NAME: Database
        SERVICE_PORT: 8080
    container_name: database
    ports:
      - "5009:8080"
    networks:
      - chess-net

  root:
    build:
      context: .
      dockerfile: Dockerfile.root
      args:
        SERVICE_NAME: JP_Morgan_Chess
        SERVICE_PORT: 8080
    container_name: jp-morgan-chess-root
    ports:
      - "5010:8080"
    networks:
      - chess-net
    stdin_open: true
    tty: true

  postgres:
    image: postgres:15
    container_name: archischach-postgres
    environment:
      POSTGRES_DB: archischach
      POSTGRES_USER: archiuser
      POSTGRES_PASSWORD: archipass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chess-net

volumes:
  postgres-data:

networks:
  chess-net:
    driver: bridge
