name: Build and test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -   name: Set up sbt
                uses: sbt/setup-sbt@v1

            -   name: Set up JVM
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '23'
            - name: Compile
              run: sbt compile
            - name: Run tests
              run: sbt clean coverage test
