name: Build and test

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from repository
            - uses: actions/checkout@v4

            - name: Set up sbt
              uses: sbt/setup-sbt@v1

            - name: Set up JVM
              uses: actions/setup-java@v4
              with:
                    distribution: 'temurin'
                    java-version: '21'
            - name: Compile
              run: sbt compile
