name: Build and test

on:
    push:
        branches: [ main, developer ]
    merge:
        branches: [main, developer]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from repository
              uses: actions/checkout@v4

            - name: Set up sbt
              uses: sbt/setup-sbt@v1
              with:
                  sbt-version: 1.10.2

            - name: Set up JVM
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '23'

            - name: Compile
              run: sbt compile

            - name: Ensure SBT cache directories exist
              run: |
                    mkdir -p ~/.ivy2/cache
                    mkdir -p ~/.sbt

            - name: Cache SBT dependencies
              uses: actions/cache@v3
              with:
                    path: |
                      ~/.ivy2/cache
                      ~/.sbt
                    key: sbt-dependencies-${{ runner.os }}-${{ hashFiles('/build.sbt') }}
                    restore-keys: |
                      sbt-dependencies-${{ runner.os }}-

            - name: Run sbt clean coverage test
              run: sbt clean coverage test

            - name: aggregate coverage
              run: sbt coverageAggregate

            - name: list coverage data
              run: ls -R target/scala-*/scoverage-data

            - name: generate coverage report
              run: sbt coverageReport

            - name: Upload coverage data to Coveralls
              run: sbt coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
